### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/PESTILLILAB.github.io#31]
Hi @anibalsolon do you understand what is wrong with this?
https://github.com/PESTILLILAB/PESTILLILAB.github.io/runs/8083204302?check_suite_focus=true

Unless "investigators:" is not an expected field I cannot find the error (It would be nice to have a preview of all the possible fields in the structure, so to use them as needed).

Thanks!

**Comment by anibalsolon** [comment]
What helps me is to copy the content to a YAML validator, like https://codebeautify.org/yaml-validator

![image](https://user-images.githubusercontent.com/562525/187335953-b15fdb60-4c33-4b3f-aa9f-90543773d521.png)

This way was possible to see that the single quote is closing earlier.

You do not need to wrap the title in quotes. One thing you can do is:
```yaml
    startDate: 2017-09-01
    endDate: 2021-12-31
    investigators: Franco Pestilli
    title: |
        NCS-FO: Connectome mapping algorithms with application to community services for big data neuroscience
```

It will be useful for titles that have colons
